services:
  onboarding_backend:
    image: onboarding/onboarding:v0
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: >
      npm run dev;

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
